Sistema_Indicadores/Controllers/MuestreoController.cs
using Sistema_Indicadores.Clases;
using Sistema_Indicadores.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;

namespace Sistema_Indicadores.Controllers
{
    public class MuestreoController : Controller
    {
        SeasonSun1213Entities15 bd = new SeasonSun1213Entities15();
        SeasonSun1213Entities16 bd1 = new SeasonSun1213Entities16();

        ProdMuestreo ProdMuestreo = new ProdMuestreo();
        ProdCamposCat ProdCamposCat = new ProdCamposCat();
        ProdProductoresCat ProdProductoresCat = new ProdProductoresCat();
        ProdAnalisis_Residuo ProdAnalisis_Residuo = new ProdAnalisis_Residuo();
        ProdMuestreoSector ProdMuestreoSector = new ProdMuestreoSector();
        Notificaciones notificaciones = new Notificaciones();

        string correo_p = "", correo_c = "", correo_i = "", compras_oportunidad = "", title="", body="", calidad="";

        public ActionResult Muestreo()
        {
            if (Session["Nombre"] != null)
            {
                ViewData["Nombre"] = Session["Nombre"].ToString();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        //Nuevo muestreo
        [HttpPost]
        public ActionResult Muestreo(ProdMuestreo model)
        {
            try
            {
                ViewData["Nombre"] = Session["Nombre"].ToString();
                var modeloExistente = bd.ProdMuestreo.FirstOrDefault(m => m.Cod_Prod == model.Cod_Prod && m.Cod_Campo == model.Cod_Campo);
                if (modeloExistente == null)
                {
                    var idAgen = bd.ProdCamposCat.Where(x => x.Cod_Prod == model.Cod_Prod && x.Cod_Campo == model.Cod_Campo).First();
                    string tipo = Convert.ToString(Session["Tipo"]);
                    var catSemanas = bd1.CatSemanas.FirstOrDefault(m => DateTime.Now >= m.Inicio && DateTime.Now <= m.Fin);

                    ProdMuestreo.IdAgen = idAgen.IdAgen;
                    ProdMuestreo.Cod_Empresa = 2;
                    ProdMuestreo.Cod_Prod = model.Cod_Prod;
                    ProdMuestreo.Cod_Campo = model.Cod_Campo;
                    ProdMuestreo.Fecha_solicitud = DateTime.Now;
                    ProdMuestreo.Telefono = model.Telefono;
                    ProdMuestreo.Inicio_cosecha = model.Inicio_cosecha;
                    ProdMuestreo.Temporada = "2122";

                    if (model.Compras_Oportunidad == "on")
                    {
                        compras_oportunidad = "S";
                    }
                    else
                    {
                        compras_oportunidad = null;
                    }
                    var camposcat = bd.ProdCamposCat.Where(x => x.Cod_Prod == model.Cod_Prod && x.Cod_Campo == model.Cod_Campo).First();
                    camposcat.Compras_Oportunidad = compras_oportunidad;
                    bd.SaveChanges();

                    if (tipo == "P")
                    {
                        ProdMuestreo.Liberacion = "S";
                    }

                    bd.ProdMuestreo.Add(ProdMuestreo);
                    bd.SaveChanges();


                    title = "Nuevo muestreo solicitado";  
                    body = "Código: " + model.Cod_Prod + " campo: " + model.Cod_Campo;
                    notificaciones.SendNotificationJSON(title, body);

                    var campo = bd.ProdCamposCat.FirstOrDefault(m => m.Cod_Prod == model.Cod_Prod && m.Cod_Campo == model.Cod_Campo);
                    var email_p = bd.SIPGUsuarios.FirstOrDefault(m => m.IdAgen == campo.IdAgen && m.Tipo == "P");
                    var email_c = bd.SIPGUsuarios.FirstOrDefault(m => m.IdAgen == campo.IdAgenC && m.Tipo == "C");
                    var email_i = bd.SIPGUsuarios.FirstOrDefault(m => m.IdAgen == campo.IdAgenI && m.Tipo == "I");

                    correo_p = email_p.correo;

                    if (email_c == null)
                    {
                        var item = bd.ProdCamposCat.Where(x => x.Cod_Prod == model.Cod_Prod && x.Cod_Campo == model.Cod_Campo).First();
                        if (Session["IdRegion"].ToString() == "3")
                        {                           
                            item.IdAgenC = 168;                           
                            correo_c = "juan.mares@giddingsfruit.mx";
                        }
                        if (Session["IdRegion"].ToString() == "1")
                        {
                            item.IdAgenC = 167;
                            correo_c = "mayra.ramirez@giddingsfruit.mx";
                        }
                        bd.SaveChanges();
                    }   
                    else
                    {
                        correo_c = email_c.correo;
                    }

                    if (email_i == null)
                    {
                        if (Session["IdRegion"].ToString() == "3")
                        {
                            correo_c = "hector.torres@giddingsfruit.mx";
                        }
                        if (Session["IdRegion"].ToString() == "1")
                        {
                            var item = bd.ProdCamposCat.Where(x => x.Cod_Prod == model.Cod_Prod && x.Cod_Campo == model.Cod_Campo).First();
                            item.IdAgenI = 205;
                            bd.SaveChanges();
                            correo_i = "jesus.palafox@giddingsfruit.mx";
                        }                       
                    }
                    else
                    {
                        correo_i = email_i.correo;
                    }

                    //correo
                    try
                    {
                        var prod = bd.ProdProductoresCat.FirstOrDefault(x => x.Cod_Prod == campo.Cod_Prod);
                        var Inicio_cosecha = String.Format("{0:d}", model.Inicio_cosecha);

                        MailMessage correo = new MailMessage();
                        correo.From = new MailAddress("indicadores.giddingsfruit@gmail.com", "Indicadores GiddingsFruit");

                        if (campo.Cod_Prod == "99999")
                        {
                            correo.To.Add("marholy.martinez@giddingsfruit.mx");
                        }

                        else
                        {
                            if (Session["Tipo"].ToString() == "P")
                            {
                                correo.To.Add(Session["Correo"].ToString());
                                correo.CC.Add(correo_c);
                                if (Session["IdAgen"].ToString() == "158" || Session["IdAgen"].ToString() == "173")
                                {
                                    if (correo_c != "maria.lopez@giddingsfruit.mx")
                                    {
                                        correo.CC.Add("maria.lopez@giddingsfruit.mx");
                                    }
                                    if (correo_i != "maria.jimenez@giddingsfruit.mx")
                                    {
                                        correo.CC.Add("maria.jimenez@giddingsfruit.mx");
                                    }
                                }
                                else
                                {
                                    correo.CC.Add(correo_i);
                                }
                            }
                            else if (Session["Tipo"].ToString() == "I")
                            {
                                correo.To.Add(Session["Correo"].ToString());
                                correo.CC.Add(correo_c);
                                correo.CC.Add(correo_p);
                            }
                            else if (Session["Tipo"].ToString() == "C")
                            {
                                correo.To.Add(Session["Correo"].ToString());
                                correo.CC.Add(correo_i);
                                correo.CC.Add(correo_p);

                                if (Session["IdRegion"].ToString() == "1")
                                {
                                    correo.CC.Add("marco.velazquez@giddingsfruit.mx");
                                }
                            }

                            if (Session["IdRegion"].ToString() == "3")
                            {
                                if (correo_c != "juan.mares@giddingsfruit.mx")
                                {
                                    correo.CC.Add("juan.mares@giddingsfruit.mx");
                                }
                                correo.CC.Add("genaro.morales@giddingsfruit.mx");
                            }

                            correo.CC.Add("oscar.castillo@giddingsfruit.mx");
                        }
                        
                        correo.Subject = "Nuevo Muestreo: " + campo.Cod_Prod;
                        correo.Body = "Solicitado por: " + Session["Nombre"].ToString() + " <br/>";
                        correo.Body += " <br/>";
                        correo.Body += "Productor: " + campo.Cod_Prod + " - " + prod.Nombre + " <br/>";
                        correo.Body += " <br/>";
                        correo.Body += "Campo: " + campo.Cod_Campo + " - " + campo.Descripcion + " <br/>";
                        correo.Body += " <br/>";
                        correo.Body += "Telefono: " + model.Telefono + "<br/>";
                        correo.Body += " <br/>";
                        correo.Body += "Inicio de cosecha: " + Inicio_cosecha + "<br/>";

                        correo.IsBodyHtml = true;
                        correo.Priority = MailPriority.Normal;

                        string sSmtpServer = "";
                        sSmtpServer = "smtp.gmail.com";

Sistema_Indicadores/Views/Muestreo/Evaluacion.cshtml
@{
    ViewBag.Title = "Evaluacion";
}

<div class="row">
    <div class="col-sm">
        @Html.DropDownList("status", (IEnumerable<SelectListItem>)ViewBag.List_Status, new { @class = "form-control form-control-sm", @id = "status" })
    </div>

    <div class="col-sm">
        <div style="float: left; margin:5px 0 5px 5px;">
            <button class="d-none d-sm-inline-block btn btn-sm shadow-lg" type="submit" id="btnN" name="btnN" style="background-color:black; border-radius: 50%;"><i class="fas fa-ban"></i></button>
        </div>
        <div style="float: left; margin:5px 0 5px 5px;">
            <button class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-lg" type="submit" id="btnR" name="btnR" style=" border-radius: 50%;"><i class="fas fa-times-circle"></i></button>
        </div>
        <div style="float: left; margin:5px 0 5px 5px;">
            <button class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-lg" type="submit" id="btnA" name="btnA" style=" border-radius: 50%;"><i class="fas fa-exclamation-triangle"></i></button>
        </div>
        <div style="float: left; margin:5px 0 5px 5px;">
            <button class="d-none d-sm-inline-block btn btn-sm btn-success shadow-lg" type="submit" id="btnV" name="btnV" style=" border-radius: 50%;"><i class="fas fa-check-circle"></i></button>
        </div>
    </div>

    <div class="col-sm">
        <div style="float: right; margin:5px 0 5px 5px;">
            <a href="@Url.Action("Evaluacion", "Muestreo")" class="d-none d-sm-inline-block btn btn-sm btn-light shadow-sm">Ver todo</a>
        </div>

        <div style="float: right; margin:5px 0 5px 0;">
            <button class="d-none d-sm-inline-block btn btn-sm btn-info shadow-lg" type="submit" id="searchC" name="searchC"><i class="fas fa-search"></i></button>
        </div>

        <div style="float: right;  margin:5px 0 5px 0">
            @Html.TextBox("cod_Prod", "", new { @class = "form-control form-control-sm", @autocomplete = "off", @placeholder = "Buscar código", @pattern = "[0-9]{5}", @maxlength = "5", @minlength = "5", @oninput = "if(this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" })
        </div>
    </div>
</div>

<div class="row">
    <div class="table-responsive table-condensed table-sm table-bordered tabla">
        <table class="table table-hover" id="dataTableEvaluacion">
            <thead class="thead-light" style="font-size:x-small; text-align:center">
                <tr>
                    <th>Asesor</th>                    
                    <th>Codigo</th>
                    <th>Productor</th>
                    <th>Campo</th>
                    <th>Ubicacion</th>
                    <th>Inicio cosecha</th>
                    <th>Fecha de entrega</th>
                    <th>Fecha de análisis</th>
                    <th>Estatus</th>
                    <th>Análisis</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<script src="~/js/Jquery/jquery-3.1.0.min.js"></script>
<script type="text/javascript">
    var estatus, cod_prod, param, query;

    $(document).ready(function () {
        if (typeof estatus === 'undefined' && typeof cod_prod === 'undefined' && typeof query === 'undefined' && typeof param === 'undefined') {
            estatus = "";
            cod_prod = "";
            query = "";
            param = "";
            tabla();
        }

        $('#btnN').click(function () {
            param = "N";
            if (typeof param != '') {
                tabla();
                vaciar();
            }
        });

        $('#btnR').click(function () {
            param = "R";
            if (typeof param != '') {
                tabla();
                vaciar();
            }
        });

        $('#btnA').click(function () {
            param = "A";
            if (typeof param != '') {
                tabla();
                vaciar();
            }
        });

        $('#btnV').click(function () {
            param = "V";
            if (typeof param != '') {
                tabla();
                vaciar();
            }
        });

        $('#searchC').click(function () {
            cod_prod = $("#cod_Prod").val();
            if (typeof cod_prod != '') {
                tabla();
                vaciar();
            }
        });

        $("#status").click(function () {
            select = $("#status option:selected").text();
            estatus = $("#status").val();
            if (typeof estatus != '--Resultado del analisis--') {
                tabla();
                vaciar();
            }
        });
    });

    function vaciar() {
        $('table tr:not(:first-child)').remove();
    }

    function tabla() {
        if (param != "") {
            query = "Muestreo/EvaluacionListF?param=" + param;
        }
        else {
            query = "Muestreo/EvaluacionList?estatus=" + estatus + "&cod_prod=" + cod_prod;
        }

        $.getJSON(siteURL + query, function (data) {
            $.each(data, function (idx, opt) {
                var analisis, retraso;
                var options = { year: 'numeric', month: 'numeric', day: 'numeric' };
                var inicio_cosecha = new Date(parseInt(opt.Inicio_cosecha.slice(6, -2)));
                var fecha_analisis = new Date(parseInt(opt.Fecha_analisis.slice(6, -2)));

                if (opt.Analisis == 'CON RESIDUOS') {
                    analisis = 'background-color:#FD7676';
                }
                else if (opt.Analisis == 'EN PROCESO') {
                    analisis = 'background-color:#D2D4D1';
                }
                else if (opt.Analisis == 'FUERA DE LIMITE') {
                    analisis = 'background-color:#F7F979';
                }
                else if (opt.Analisis == 'LIBERADO') {
                    analisis = 'background-color:#9BFC6E';
                }
                if (opt.Dias > 5) {
                    retraso = 'background-color:#FD7676';
                }
                else if (opt.Dias > 3) {
                    retraso = 'background-color:#F7F979';
                }
                else if (opt.Dias < 3) {
                    retraso = 'background-color:#9BFC6E';
                }

                $('#dataTableEvaluacion').append(
                    '<tr><td>' + opt.Asesor +
                    '</td><td>' + opt.Cod_Prod +
                    '</td><td>' + opt.Productor +
                    '</td><td>' + opt.Campo +
                    '</td><td>' + opt.Ubicacion +
                    '</td><td style="' + retraso + '">' + inicio_cosecha.toLocaleDateString("es-ES", options) +
                    '</td><td>' + opt.Fecha_real +
                    '</td><td>' + fecha_analisis.toLocaleDateString("es-ES", options) +
                    '</td><td>' + opt.Estatus +
                    '</td><td style="' + analisis + '">' + opt.Analisis +
                    '</td></tr>');
            });
        }, 'json');
    }
</script>

Sistema_Indicadores/Views/Muestreo/Resultados_Analisis.cshtml
@model IEnumerable<Sistema_Indicadores.Clases.ClassMuestreo>

@{
    ViewBag.Title = "Resultados_Analisis";
}

<h6>ANALISIS DE RESIDUOS DE PLAGUICIDAS TEMPORADA 2021-2022</h6>
<div class="row">
    <div class="col-sm-12 table-responsive">
        @using (Html.BeginForm("Resultados_Analisis", "Muestreo", FormMethod.Get))
        {

            <div style="float: left; margin:5px 0 5px 5px;">
                <div style="float: left;">
                    @Html.DropDownList("status", (IEnumerable<SelectListItem>)ViewBag.List_Status, new { @class = "form-control form-control-sm" })
                </div>
                <div style="float: right;">
                    <button class="d-none d-sm-inline-block btn btn-sm btn-info shadow-lg" type="submit" name="searchS"><i class="fas fa-search"></i></button>
                </div>
            </div>

            if ((short)Session["IdAgen"] == 205 || Session["IdAgen"].ToString() == "153" || Session["IdAgen"].ToString() == "281" || Session["IdAgen"].ToString() == "1")
            {
                <div style="float: left; margin:5px 0 5px 5px;">
                    <div style="float: left;">
                        @Html.DropDownList("c_zona", new SelectList(ViewBag.List_Zona, "Codigo", "DescZona"), "--Seleccione una zona--", new { @class = "form-control form-control-sm", @id = "c_zona" })
                    </div>
                    <div style="float: right;">
                        <button class="d-none d-sm-inline-block btn btn-sm btn-info shadow-lg" type="submit" name="btnZona"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            }

            <div style="float: right; margin:5px 0 5px 5px;">
                <a href="@Url.Action("Resultados_Analisis", "Muestreo")" class="d-none d-sm-inline-block btn btn-sm btn-light shadow-sm">Ver todo</a>
            </div>

            <div style="float: right; margin:5px 0 5px 0;">
                <button class="d-none d-sm-inline-block btn btn-sm btn-info shadow-lg" type="submit" id="searchC" name="searchC"><i class="fas fa-search"></i></button>
            </div>

            <div style="float: right;  margin:5px 0 5px 0">
                @Html.TextBox("cod_prod", "", new { @class = "form-control form-control-sm", @autocomplete = "off", @placeholder = "Buscar código", @pattern = "[0-9]{5}", @maxlength = "5", @minlength = "5", @oninput = "if(this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" })
            </div>
        }
    </div>
    </div>

<div class="row">
    <div class="table-responsive table-condensed table-sm table-bordered tabla">
        <table class="table table-hover" id="dataTableResultadosA">
            @if (Model != null)
            {
                <thead class="thead-light" style="font-size:x-small; text-align:center">
                    <tr>
                        <th>Codigo</th>
                        <th>Campo</th>
                        <th>Sector</th>
                        <th>Productor</th>
                        <th>Tipo</th>
                        <th>Producto</th>
                        <th>Zona</th>
                        <th>Envío</th>
                        <th>Entrega</th>
                        <th>Status</th>
                        <th>Análisis</th>
                        <th>Lab</th>
                        <th>LiberacionUSA</th>
                        <th>LiberacionEU</th>
                        <th>Trazas</th>
                        <th>Comentarios</th>
                        <th>Fecha</th>
                    </tr>
                </thead>
                @*<tbody>
                        <tr>
                        </tr>
                    </tbody>*@
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cod_Prod)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cod_Campo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Sector)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Productor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tipo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Producto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DescZona)
                        </td>
                        <td>
                            @(String.Format("{0:dd/MM/yyyy}", item.Fecha_envio))
                        </td>
                        <td>
                            @(String.Format("{0:dd/MM/yyyy}", item.Fecha_entrega))
                        </td>

                        @if (item.Analisis == "R")
                        {
                            <td style="background-color: #FD7676"> CON RESIDUOS </td>
                        }
                        else if (item.Analisis == "P")
                        {
                            <td style="background-color: #D2D4D1"> EN PROCESO </td>
                        }
                        else if (item.Analisis == "F")
                        {
                            <td style="background-color: #F7F979"> FUERA DEL LIMITE </td>
                        }
                        else if (item.Analisis == "L")
                        {
                            <td style="background-color: #9BFC6E"> LIBERADO </td>
                        }
                        <td>
                            @Html.DisplayFor(modelItem => item.Num_analisis)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Laboratorio)
                        </td>
                        <td>
                            @(String.Format("{0:dd/MM/yyyy}", item.LiberacionUSA))
                        </td>
                        <td>
                            @(String.Format("{0:dd/MM/yyyy}", item.LiberacionEU))
                        </td>
                        @if (item.Trazas == "1")
                        {
                            <td> SI </td>
                        }
                        else
                        {
                            <td> NO </td>
                        }
                        <td>
                            @Html.DisplayFor(modelItem => item.Comentarios)
                        </td>
                        <td>
                            @(String.Format("{0:dd/MM/yyyy}", item.Fecha))
                        </td>
                    </tr>
                    }
                </tbody>
            }
            else
            {
                <tr>
                    <td colspan="17">No se encontró ningún dato</td>
                </tr>
            }
        </table>
    </div>
</div>

<script src="~/js/Jquery/jquery-3.1.0.min.js"></script>
<script type="text/javascript">
    var estatus, c_zona, cod_prod;

    $(document).ready(function () {
        
    });

    if (typeof estatus === 'undefined' && typeof c_zona === 'undefined' && typeof cod_prod === 'undefined') {
        estatus = "";
        c_zona = "";
        cod_prod = "";
        tabla();
    }

    $('#searchC').click(function () {
        cod_prod = $("#cod_Prod").val();
        if (typeof cod_prod != '') {
            tabla();
            vaciar();
        }
    });

    $("#status").click(function () {
        select = $("#status option:selected").text();
        estatus = $("#status").val();
        if (typeof estatus != '--Resultado del analisis--') {
            tabla();
            vaciar();
        }
    });

    $("#c_zona").click(function () {
        select = $("#c_zona option:selected").text();
        c_zona = $("#c_zona").val();
        if (typeof estatus != '') {
            tabla();
            vaciar();
        }
    });

    function vaciar() {
        $('table tr:not(:first-child)').remove();
    }

    function tabla() {
        $.getJSON(siteURL + "Muestreo/Resultados_Analisis_List?estatus=" + estatus + "&c_zona=" + c_zona + "&cod_prod=" + cod_prod, function (data) {
            $.each(data, function (idx, opt) {
                var status_style, status;
                var options = { year: 'numeric', month: 'numeric', day: 'numeric' };
                var Fecha_envio = new Date(parseInt(opt.Fecha_envio.slice(6, -2)));
                var Fecha_entrega = new Date(parseInt(opt.Fecha_entrega.slice(6, -2)));
                var LiberacionUSA = new Date(parseInt(opt.LiberacionUSA.slice(6, -2)));
                var LiberacionEU = new Date(parseInt(opt.LiberacionEU.slice(6, -2)));
                var Fecha = new Date(parseInt(opt.Fecha.slice(6, -2)));

                if (opt.Estatus == 'R') {
                    status = 'CON RESIDUOS';
                    status_style = 'background-color:#FD7676';
                }
                else if (opt.Estatus == 'P') {
                    status = 'EN PROCESO';
                    status_style = 'background-color:#D2D4D1';
                }
                else if (opt.Estatus == 'F') {
                    status = 'FUERA LIMITE';
                    status_style = 'background-color:#F7F979';
                }
                else if (opt.Estatus == 'L') {
                    status = 'LIBERADO';
                    status_style = 'background-color:#9BFC6E';
                }

                $('#dataTableResultadosA').append('<tr><td>' + opt.Cod_Prod + '</td><td>' + opt.Cod_Campo + '</td><td>' + opt.Sector + '</td><td>' + opt.Productor + '</td><td>' + opt.Tipo + '</td><td>' + opt.Producto + '</td><td>' + opt.Zona + '</td><td>' + Fecha_envio.toLocaleDateString("es-ES", options) + '</td><td>' + Fecha_entrega.toLocaleDateString("es-ES", options) + '</td><td style="' + status_style + '">' + status + '</td><td>' + opt.Num_analisis + '</td><td>' + opt.Laboratorio + '</td><td>' + LiberacionUSA.toLocaleDateString("es-ES", options) + '</td><td>' + LiberacionEU.toLocaleDateString("es-ES", options) + '</td><td>' + opt.Trazas + '</td><td>' + opt.Comentarios + '</td><td>' + Fecha.toLocaleDateString("es-ES", options) + '</td></tr>');
            });
        }, 'json');
    }
</script>